//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outfit
    {
        public int OutfitID { get; set; }
        public string OutfitSeason { get; set; }
        public string OutfitOccasion { get; set; }
        public int TopID { get; set; }
        public int BottomID { get; set; }
        public int ShoeID { get; set; }
        public int AccessoryID { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Bottom Bottom { get; set; }
        public virtual Outfit Outfits1 { get; set; }
        public virtual Outfit Outfit1 { get; set; }
        public virtual Outfit Outfits11 { get; set; }
        public virtual Outfit Outfit2 { get; set; }
        public virtual Shoe Sho { get; set; }
        public virtual Top Top { get; set; }
    }
}
